sys info page now writes to a file

diff --git a/sys_info_page b/sys_info_page
--- a/sys_info_page
+++ b/sys_info_page
@@ -13,12 +13,14 @@ report_uptime () {
 		_EOF_
 }
 
+
 report_disk_space () {
 	cat <<- _EOF_
 		<H2>Disk Space Utilization</H2>
 		<PRE>$(df -h)</PRE>
 		_EOF_
 }
+
 
 report_home_space () {
 	if [[ $(id -u) -eq 0 ]]; then
@@ -35,17 +37,86 @@ report_home_space () {
 	return
 }
 
-cat << _EOF_
-<HTML>
-	<HEAD>
-		<TITLE>$TITLE</TITLE>
-	</HEAD>
-	<BODY>
-		<H1>$TITLE</H1>
-		<P>$TIME_STAMP</P>
-		$(report_uptime)
-		$(report_disk_space)
-		$(report_home_space)
-	</BODY>
-</HTML>
-_EOF_
+
+usage() {
+	echo "$PROGNAME: usage: $PROGNAME [-f file | -i]"
+	return
+}
+
+write_html_page() {
+	cat <<- _EOF_
+	<HTML>
+		<HEAD>
+			<TITLE>$TITLE</TITLE>
+		</HEAD>
+		<BODY>
+			<H1>$TITLE</H1>
+			<P>$TIME_STAMP</P>
+			$(report_uptime)
+			$(report_disk_space)
+			$(report_home_space)
+		</BODY>
+	</HTML>
+	_EOF_
+}
+
+
+
+# process command line options
+
+interactive=
+filename=
+
+while [[ -n $1 ]]; do
+	case $1 in
+		-f | --file)		shift
+							filename=$1
+							;;
+		-i | --interactive)	interactive=1
+							;;
+		-h | --help)			usage
+							exit
+							;;
+		*)					usage >&2
+							exit 1
+							;;
+	esac
+	shift
+done
+
+# interactive mode!
+
+if [[ -n $interactive ]]; then
+	while true; do
+		read -p "Enter the name of output file: " filename
+		if [[ -e $filename ]]; then
+			read -p "$filename exists. Overwrite this file? [y/n/q] > "
+			case $REPLY in
+				Y | y)	break
+						;;
+				Q | q)	echo "Program terminated."
+						exit
+						;;
+				*)		continue
+						;;
+			esac
+		elif [[ -z $filename ]]; then
+			continue
+		else
+			break
+		fi
+	done
+fi
+
+# output HTML page
+
+if [[ -n $filename ]]; then
+	if touch $filename && [[ -f $filename ]]; then
+		write_html_page > $filename
+	else
+		echo "$PROGNAME: Cannot write file '$filename'" >&2
+		exit 1
+	fi
+else
+	write_html_page
+fi
