changing large if statement to case

diff --git a/sys_info_report b/sys_info_report
--- a/sys_info_report
+++ b/sys_info_report
@@ -2,51 +2,36 @@
 
 # sys_info_report: a menu driven system information program
 
-DELAY=3
+clear
+cat <<- _EOF_ 
+	Please Select:
 
-while true; do
+	1. Display System Information
+	2. Display Disk Space
+	3. Display Home Space Utilization
+	0. Quit
+_EOF_
 
-	clear
-	cat <<- _EOF_ 
-		Please Select:
+read -p "Enter Selection [0-3] > "
 
-		1. Display System Information
-		2. Display Disk Space
-		3. Display Home Space Utilization
-		0. Quit
-	_EOF_
-
-	read -p "Enter Selection [0-3] > "
-
-	if [[ $REPLY =~ ^[0-3]$ ]]; then
-		if [[ $REPLY == 1 ]]; then
-			echo "Hostname: $HOSTNAME"
-			uptime
-			sleep $DELAY
-			continue
-		fi
-		if [[ $REPLY == 2 ]]; then
-			df -h
-			sleep $DELAY
-			continue
-		fi
-		if [[ $REPLY == 3 ]]; then
-			if [[ $(id -u) -eq 0 ]]; then
-				echo "Home Space Utilization (All Users)"
-				du -sh /home/*
-			else
-				echo "Home Space Utilization ($USER)"
-				du -sh $HOME
-			fi
-			sleep $DELAY
-			continue
-		fi
-		if [[ $REPLY == 0 ]]; then
-			break
-		fi
-	else
-		echo "Invalid entry." >&2
-		sleep $DELAY
-	fi
-done
-echo "Program terminated."
+case $REPLY in 
+	0)	echo "Program terminated."
+		exit
+		;;
+	1)	echo "Hostname: $HOSTNAME"
+		uptime
+		;;
+	2)	df -h 
+		;;
+	3)	if [[ $(id -u) -eq 0 ]]; then
+			echo "Home Space Utilization (All Users)"
+			du -sh /home/*
+		else
+			echo "Home Space Utilization ($USER)"
+			du -sh $HOME 
+		fi 
+		;;
+	*)	echo "Invalid entry:" >&2
+		exit 1
+		;;
+esac
